version: 2.1
<<<<<<< HEAD
jobs:
  step-one:
    docker:
      - image: circleci/node:12.18.2-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test:once
      - run: npm run build

workflows:
    main:
      jobs:
        - step-one
=======
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
workflows:
    build-and-test:
      jobs:
        - build-and-test
>>>>>>> c86218d5e4a8b95d3b87ea1f698cd54de8522d28
